### ISSUE TITLE
[Bug]: Traefik using 100% CPU power to obtain SSL certificate

### ISSUE THREAD

**Issue by deployn** [coollabsio/coolify#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm using Coolify on my server, today I couldn't reach any service anymore. Maybe it is related to #960.

The problem is traefik uses all the CPU power available to obtain a certificate?

![image](https://user-images.githubusercontent.com/54767886/230776165-b82349df-bc2a-4017-81a2-f8f00ac2753a.png)

I restarted the server, the problem came back four hours later. I restarted again, and the problem is here again, four hours later.

Log of the coolify container:

```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })
    at RequestHandler.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:35033:13)
    at RequestHandler.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:34996:12)
    at RequestHandler.request (/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:34991:12)
    at async PrismaClient._request (/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:36082:16)
    at async proxyConfiguration (/app/routes/webhooks/traefik/handlers.js:244:29) {
  clientVersion: '4.8.1',
  batchRequestIdx: undefined
}
```

Log of the traefik container:

```
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 1.06680567s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 4.461442789s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 1.660496187s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 3.079001596s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 557.487367ms" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 993.320114ms" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 400.511773ms" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 1.803194475s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 4.996652137s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 1.240275483s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 8.250202842s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 10.433872959s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 1.162634936s" providerName=acme
time="2023-03-25T10:07:46Z" level=error msg="Error getting challenge for token retrying in 18.772722881s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 635.109057ms" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 11.273638295s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 12.920123866s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 1.489574712s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 7.199134956s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 3.711563735s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 9.013768291s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 360.015238ms" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 2.249935131s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 621.673443ms" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 1.05521742s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 6.483162206s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 719.95238ms" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 1.50584083s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 5.757326401s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 939.60806ms" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 1.024561307s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 2.434809323s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 2.676992653s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 4.424679595s" providerName=acme
time="2023-03-25T10:07:47Z" level=error msg="Error getting challenge for token retrying in 10.894801159s" providerName=acme
```

Do you know what I can do to prevent this behavior?

### Steps To Reproduce

1. Install coolify
2. Add services with different domains
3. Wait 3–4 hours

### Version

3.12.30

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
