### ISSUE TITLE
[Bug]: Issue deploying Nodejs project

### ISSUE THREAD

**Issue by dediamond1** [coollabsio/coolify#1978]
### Description

NODEJS PROJECT / SERVER DEPLOYMENT ISSUE

### Minimal Reproduction (if possible, example repository)

I was testing the system, but each time i try to deploy a node project.

1. It crushes `500 Something is not okay`
2. it keeps loading and loading.

![Screenshot 2024-04-12 at 21 50 01](https://github.com/coollabsio/coolify/assets/21068293/764f0478-c151-4397-961a-dd8af58e97ee)

Otherwise amazing work!

### Version

4.0.0-beta.256

**Comment by andrasbacsai** [comment]
Based on the image, it seems that you are running a self-hosted version. It appears that the Redis container that Coolify starts is not running. 

Can you please check if it's running properly?

**Comment by dediamond1** [comment]
> Based on the image, it seems that you are running a self-hosted version. It appears that the Redis container that Coolify starts is not running.
> 
> Can you please check if it's running properly?


Its working now. thanks alot!


i am testing mongodb. how can i change the mongodb default db name `test` to any name of choice?

MONGODB_URI=mongodb://root:zobFryH4RjGVZorVwDI36mIqKUrvR6S82eumrKvR1LDyEcnz5t5G1vlgdQKQ1IBr@164.92.185.222:5436/techdevcyber?directConnection=true

**Comment by dediamond1** [comment]
> > Based on the image, it seems that you are running a self-hosted version. It appears that the Redis container that Coolify starts is not running.
> > Can you please check if it's running properly?
> 
> Its working now. thanks alot!
> 
> i am testing mongodb. how can i change the mongodb default db name `test` to any name of choice? basically my node server doesnt connect to mongodb when i provide specific db name. am i missing something 😃?
> 
> `MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://" at new ConnectionString (/app/node_modules/mongodb-connection-string-url/lib/index.js:86:19) at parseOptions (/app/node_modules/mongodb/lib/connection_string.js:188:17) at new MongoClient (/app/node_modules/mongodb/lib/mongo_client.js:46:63) at /app/node_modules/mongoose/lib/connection.js:802:16 at new Promise (<anonymous>) at Connection.openUri (/app/node_modules/mongoose/lib/connection.js:799:19) at /app/node_modules/mongoose/lib/index.js:414:10 `
> 
> this is how i am doing. `MONGODB_URI=mongodb://root:zobFryH4RjGVZorVwDI36mIqKUrvR6S82eumrKvR1LDyEcnz5t5G1vlgdQKQ1IBr@164.92.185.222:5436/techdevcyber?directConnection=true`

without the name the connect is working.

**Comment by dediamond1** [comment]
> Based on the image, it seems that you are running a self-hosted version. It appears that the Redis container that Coolify starts is not running.
> 
> Can you please check if it's running properly?

it working. thanks
