### ISSUE TITLE
[Bug]: MongoDB fails when provided specific db name

### ISSUE THREAD

**Issue by dediamond1** [coollabsio/coolify#1986]
### Description

i am testing mongodb. how can i change the mongodb default db name test to any name of choice?

### Minimal Reproduction (if possible, example repository)

i am testing mongodb. how can i change the mongodb default db name test to any name of choice?
basically my node server doesnt connect to mongodb when i provide specific db name. am i missing something 😃?

```
/Users/test/Desktop/desk/testproject/node_modules/mongodb/lib/cmap/connection.js:231
callback(new error_1.MongoServerError(document));
^

MongoServerError: Authentication failed.
at Connection.onMessage (/Users/test/Desktop/desk/testproject/node_modules/mongodb/lib/cmap/connection.js:231:30)
at MessageStream. (/Users/test/Desktop/desk/testproject/node_modules/mongodb/lib/cmap/connection.js:61:60)
at MessageStream.emit (node:events:517:28)
at processIncomingData (/Users/test/Desktop/desk/testproject/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
at MessageStream._write (/Users/test/Desktop/desk/testproject/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
at writeOrBuffer (node:internal/streams/writable:392:12)
at _write (node:internal/streams/writable:333:10)
at Writable.write (node:internal/streams/writable:337:10)
at Socket.ondata (node:internal/streams/readable:777:22)
at Socket.emit (node:events:517:28)
at addChunk (node:internal/streams/readable:335:12)
at readableAddChunk (node:internal/streams/readable:308:9)
at Readable.push (node:internal/streams/readable:245:10)
at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
ok: 0,
code: 18,
codeName: 'AuthenticationFailed',
connectionGeneration: 0,
[Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}

Node.js v18.18.2
[nodemon] app crashed - waiting for file changes before starting...
```

this is how i am doing. `MONGODB_URI=mongodb://root:zobFryH4RjGVZorVwDI36mIqKUrvR6S82eumrKvR1LDyEcnz5t5G1vlgdQKQ1IBr@164.92.185.222:5436/techdevcyber?directConnection=true`

### Version

4.0.0-beta.258

**Comment by andrasbacsai** [comment]
I cannot reproduce the issue. Is this still occurs?

**Comment by ohyajk** [comment]
@andrasbacsai  Yes, If you add db name after user:pass@ip/**dbname** It does not connect. If I don't give a db name then all data is saved in test db.

**Comment by plutack** [comment]
I can confirm the same on version v4.0.0-beta.318

**Comment by binhodev** [comment]
Worked normally, you need add a flag "authSource=admin"

Example:
`mongodb://<user>:<userpassword>@<address_server>:<port>/<database_name>?authSource=admin&directConnection=true`

Now, you can create many mongodb databases.

**Comment by ohyajk** [comment]
Thanks, I will try this

**Comment by peaklabs-dev** [comment]
This is more of an improvement request as it has not yet been implemented - setting the database name over the UI and auto ajusting the URL, please move further discussion to the following [discussion](https://github.com/coollabsio/coolify/discussions/3978).
