### ISSUE TITLE
[Bug]: Redeploy hangs on No logs yet.

### ISSUE THREAD

**Issue by dkonsoftware** [coollabsio/coolify#2282]
### Description

Hi, i tried to redeploy apps on multiple servers but it hangs on No logs yet.
I downgraded coolify from latest 285 to 277 (last working version) and still same issue.
Simillar issue to this #2186
any ideas?

### Minimal Reproduction (if possible, example repository)

Logs from coolify container:

```
2024-05-23 14:10:00 Running ['artisan' horizon:snapshot] ........ 437ms DONE
  ⇂ '/usr/bin/php8.2' 'artisan' horizon:snapshot > '/dev/null' 2>&1
  2024-05-23 14:10:01 Running [App\Jobs\CleanupInstanceStuffsJob] ... 2ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ContainerStatusJob] ......... 8ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ContainerStatusJob] ......... 1ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ContainerStatusJob] ......... 1ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ContainerStatusJob] ......... 1ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ContainerStatusJob] ......... 1ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ServerStatusJob] ............ 1ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ServerStatusJob] ............ 1ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ServerStatusJob] ............ 1ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ServerStatusJob] ............ 2ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\ServerStatusJob] ............ 5ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\PullHelperImageJob] ......... 2ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\PullHelperImageJob] ......... 2ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\PullHelperImageJob] ......... 2ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\PullHelperImageJob] ......... 2ms DONE
  2024-05-23 14:10:01 Running [App\Jobs\PullHelperImageJob] ......... 2ms DONE
  2024-05-23 14:10:01 Running ['artisan' uploads:clear] ........... 489ms DONE
  ⇂ '/usr/bin/php8.2' 'artisan' uploads:clear > '/dev/null' 2>&1

  2024-05-23 14:11:00 Running [App\Jobs\ContainerStatusJob] ........ 10ms DONE
  2024-05-23 14:11:00 Running [App\Jobs\ContainerStatusJob] ......... 1ms DONE
  2024-05-23 14:11:00 Running [App\Jobs\ContainerStatusJob] ......... 1ms DONE
  2024-05-23 14:11:00 Running [App\Jobs\ContainerStatusJob] ......... 1ms DONE
  2024-05-23 14:11:00 Running [App\Jobs\ContainerStatusJob] ......... 1ms DONE
  2024-05-23 14:11:00 Running [App\Jobs\ServerStatusJob] ............ 1ms DONE
  2024-05-23 14:11:00 Running [App\Jobs\ServerStatusJob] ............ 1ms DONE
  2024-05-23 14:11:00 Running [App\Jobs\ServerStatusJob] ............ 1ms DONE
  2024-05-23 14:11:00 Running [App\Jobs\ServerStatusJob] ............ 1ms DONE
  2024-05-23 14:11:00 Running [App\Jobs\ServerStatusJob] ............ 1ms DONE
```
### Exception or Error
```
[2024-05-23 18:44:11] production.ERROR: mux_client_request_session: session request failed: Session open refused by peer
ControlSocket /var/www/html/storage/app/ssh/mux/[server_ip]_root already exists, disabling multiplexing
 {"exception":"[object] (RuntimeException(code: 0): mux_client_request_session: session request failed: Session open refused by peer

ControlSocket /var/www/html/storage/app/ssh/mux/[server_ip]_root already exists, disabling multiplexing

 at /var/www/html/app/Traits/ExecuteRemoteCommand.php:89)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): App\\Jobs\\ApplicationDeploymentJob->App\\Traits\\{closure}()
#1 /var/www/html/app/Traits/ExecuteRemoteCommand.php(27): Illuminate\\Support\\Collection->each()
#2 /var/www/html/app/Jobs/ApplicationDeploymentJob.php(701): App\\Jobs\\ApplicationDeploymentJob->execute_remote_command()
#3 /var/www/html/app/Jobs/ApplicationDeploymentJob.php(505): App\\Jobs\\ApplicationDeploymentJob->check_image_locally_or_remotely()
#4 /var/www/html/app/Jobs/ApplicationDeploymentJob.php(300): App\\Jobs\\ApplicationDeploymentJob->deploy_nixpacks_buildpack()
#5 /var/www/html/app/Jobs/ApplicationDeploymentJob.php(247): App\\Jobs\\ApplicationDeploymentJob->decide_what_to_do()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\ApplicationDeploymentJob->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#26 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#33 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#35 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#36 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#37 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#39 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#40 {main}
"}

[2024-05-23 21:40:55] production.ERROR: mux_client_request_session: session request failed: Session open refused by peer
ControlSocket /var/www/html/storage/app/ssh/mux/[server_ip]_root already exists, disabling multiplexing
fatal: invalid object name 'mux_client_request_session'.
 {"exception":"[object] (RuntimeException(code: 0): mux_client_request_session: session request failed: Session open refused by peer

ControlSocket /var/www/html/storage/app/ssh/mux/[server_ip]_root already exists, disabling multiplexing

fatal: invalid object name 'mux_client_request_session'.
 at /var/www/html/app/Traits/ExecuteRemoteCommand.php:89)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): App\\Jobs\\ApplicationDeploymentJob->App\\Traits\\{closure}()
#1 /var/www/html/app/Traits/ExecuteRemoteCommand.php(27): Illuminate\\Support\\Collection->each()
#2 /var/www/html/app/Jobs/ApplicationDeploymentJob.php(1201): App\\Jobs\\ApplicationDeploymentJob->execute_remote_command()
#3 /var/www/html/app/Jobs/ApplicationDeploymentJob.php(475): App\\Jobs\\ApplicationDeploymentJob->clone_repository()
#4 /var/www/html/app/Jobs/ApplicationDeploymentJob.php(296): App\\Jobs\\ApplicationDeploymentJob->deploy_dockerfile_buildpack()
#5 /var/www/html/app/Jobs/ApplicationDeploymentJob.php(247): App\\Jobs\\ApplicationDeploymentJob->decide_what_to_do()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\ApplicationDeploymentJob->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#26 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#33 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#35 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#36 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#37 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#39 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#40 {main}
"}
```
### Version

285, 277

**Comment by peaklabs-dev** [comment]
@dkonsoftware  Can you please update to the latest version and recheck and if possible provide more detailed reproduction steps? Thank you.

**Comment by peaklabs-dev** [comment]
Due to inactivity, we're closing this issue. Feel free to reopen the issue and provide the requested details if the problem is still present with the latest version.
