### ISSUE TITLE
[Bug]: outbound http requests TIMEOUT

### ISSUE THREAD

**Issue by Khaledgarbaya** [coollabsio/coolify#2534]
### Description

I am self hosting my Remix App on a Hetzner cloud server. I am not able to make a call to an external API endpoin, the resend API in this case.
I have a firewall config that include all the ports mentioned by Coolify docs.
All outbound traffic is allowed.

This is the error I get from the log.
```
sendEmail FetchError: request to https://api.resend.com/emails failed, reason: connect ETIMEDOUT 34.32.135.56:443
    at ClientRequest.<anonymous> (/app/node_modules/.pnpm/@remix-run+web-fetch@4.4.2/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1800:11)
    at ClientRequest.emit (node:events:532:35)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: 'connect'
}
```

I already contacted the resend team and they told that they are not blocking any traffic from hetzner.

I would appreciate any help here, I am aware that this may not be a coolify problem also.

Thanks again for building such an amazing product

### Minimal Reproduction (if possible, example repository)

- Buy a hetzner server
- install Coolify v4.0.0-beta.297
- create a new project
- deploy a remix app to the created project
- use nixpack for building
- in the app make a call to the resend API

### Exception or Error

sendEmail FetchError: request to https://api.resend.com/emails failed, reason: connect ETIMEDOUT 34.32.135.56:443
    at ClientRequest.<anonymous> (/app/node_modules/.pnpm/@remix-run+web-fetch@4.4.2/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1800:11)
    at ClientRequest.emit (node:events:532:35)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: 'connect'
}

### Version

v4.0.0-beta.297

**Comment by andrasbacsai** [comment]
This issue is not related to Coolify itself.

Can you please execute the following commands on your server and show me the output?

1. `curl ``[https://api.resend.com/emails](https://api.resend.com/emails)`
2. `docker exec coolify sh -c "curl -s ``[https://api.resend.com/emails](https://api.resend.com/emails)``"`

**Comment by Khaledgarbaya** [comment]
@andrasbacsai for some reason now everything works fine 🎉  It's indeed not coolify itself. Apparently was an issue on the resend side.
Appreciate your help and thanks again for the amazing product

**Comment by Khaledgarbaya** [comment]
Some more update for folks having a similar issue.

From the resend team: 

> The connectivity problems are due to sanctions or abusive behaviours associated with certain IPs/ranges from Hetzner that have been flagged and blocked by major cloud providers. Unfortunately, we do not have control over this.

There's a few reports on forums and blog posts about this situation.

As a workaround, I recommend rotating the public IP of your application to ensure it falls within a different range and try to communicate with our API again.

For my case I did not need to do that and the ip was unblocked
