### ISSUE TITLE
[Bug]: Application unable to resolve database service container name

### ISSUE THREAD

**Issue by shadysamir** [coollabsio/coolify#3369]
### Description

Self hosted coolify. I created a project, added postgres service, added NocoDB application and set the NC_DB variable to connect to postgres sevice. NocoDB is unable to start because it can't resolve the PG container name. Error from NocoDB logs:
```
Error: Error: getaddrinfo EAI_AGAIN j4g44okskok04cks4kwogkkg
```

### Minimal Reproduction (if possible, example repository)

Create project
Create postgres service
Create NocoDB application but do not deploy yet.
Set environment variable in NovoDB application NC_DB to `pg://<hostname>:5432?u=<username>&p=<password>&d=<database_name>`
Deploy NocoDB

### Exception or Error

[Nest] 9  - 09/07/2024, 7:31:25 PM   ERROR ;5;3m[ExceptionHandler] Error: getaddrinfo EAI_AGAIN j4g44okskok04cks4kwogkkg
Error: Error: getaddrinfo EAI_AGAIN j4g44okskok04cks4kwogkkg
    at NcConfig.create (/usr/src/app/docker/main.js:2:2228217)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1830025)
    at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
    at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)

### Version

v4.0.0-beta.331

### Cloud?

- [ ] Yes
- [X] No

**Comment by shadysamir** [comment]
Definitely worked!! Thank you! 🙌
