### ISSUE TITLE
[Bug]: ENV VARIABLES WITH SPACE RESULTS IN ERRORS 

### ISSUE THREAD

**Issue by lewismunene020** [coollabsio/coolify#3430]
## Description

When loading the .env file in the root directory of the project, a FormatException is thrown by the Symfony\Component\Dotenv\Dotenv class. The error message indicates that a value containing spaces must be surrounded by quotes.

## For php laravel  or  codeignitor code  there is  an issue . since  coolify comes  with  :
```
COOLIFY_PROJECT_NAME=
COOLIFY_CONTAINER_NAME=
COOLIFY_APP_NAME=
COOLIFY_SERVER_IP=
COOLIFY_ENVIRONMENT_NAME=
COOLIFY_PROJECT_NAME=


```

Best Fix is  to  have environment  variables  with spaces  in  the  value after equal sign  wrapped with quotes to  avoid  issues 

## Steps to Reproduce:

Create a new .env file in the root directory of the project.
Add a value containing spaces without surrounding quotes, e.g. NAME=ENV VARIABLES
Run the application.

Expected Behavior:

The application should load the .env file without throwing an error.

Actual Behavior:

A FormatException is thrown by the Symfony\Component\Dotenv\Dotenv class.

### Exception or Error

Error Message:

Fatal error: Uncaught Symfony\Component\Dotenv\Exception\FormatException: A value containing spaces must be surrounded by quotes in "/var/www/html/.env" at line 9. ...ME=ENV VARIABLES\nBROADCAST_DRIVER=lo... ^ line 9 offset 361 in /var/www/html/vendor/symfony/dotenv/Dotenv.php:547

Stack Trace:

#0 /var/www/html/vendor/symfony/dotenv/Dotenv.php(373): Symfony\Component\Dotenv\Dotenv->createFormatException() #1 /var/www/html/vendor/symfony/dotenv/Dotenv.php(250): Symfony\Component\Dotenv\Dotenv->lexValue() #2 /var/www/html/vendor/symfony/dotenv/Dotenv.php(557): Symfony\Component\Dotenv\Dotenv->parse() #3 /var/www/html/vendor/symfony/dotenv/Dotenv.php(81): Symfony\Component\Dotenv\Dotenv->doLoad() #4 /var/www/html/index.php(242): Symfony\Component\Dotenv\Dotenv->load() #5 {main}

### Version

v4.0.0-beta.335

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
The next release will have a fix for this.

**Comment by lewismunene020** [comment]
Thanks @andrasbacsai .Waiting for next release
