### ISSUE TITLE
[Bug]: HeyForm NOAUTH Authentication required

### ISSUE THREAD

**Issue by Syiana** [coollabsio/coolify#4217]
### Error Message and Logs

2024-11-09T13:29:30.351887354Z [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
2024-11-09T13:29:30.351909246Z     at parseError (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
2024-11-09T13:29:30.351913082Z     at parseType (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
2024-11-09T13:29:30.358864101Z /app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179
2024-11-09T13:29:30.358875699Z     return new ReplyError(string)
2024-11-09T13:29:30.358878824Z            ^
2024-11-09T13:29:30.358881528Z 
2024-11-09T13:29:30.358884081Z ReplyError: NOAUTH Authentication required.
2024-11-09T13:29:30.358886555Z     at parseError (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
2024-11-09T13:29:30.358889209Z     at parseType (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14) {
2024-11-09T13:29:30.358892274Z   command: { name: 'select', args: [ '1' ] }
2024-11-09T13:29:30.358894878Z }
2024-11-09T13:29:30.358897321Z 
2024-11-09T13:29:30.358900045Z Node.js v18.20.0

### Steps to Reproduce

1. Select HeyForm Template
2. Deploy
3. Service crashes

### Coolify Version

v4.0.0-beta.364

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by cr4zyiw4n** [comment]
i can confirm, i have the same error

Also at version 4.0.0-beta.367

**Comment by corentinclichy** [comment]
Same error here

**Comment by Syiana** [comment]
environment:
      - SERVICE_FQDN_HEYFORM_8000
      - 'APP_HOMEPAGE_URL=${SERVICE_FQDN_HEYFORM}'
      - 'SESSION_KEY=${SERVICE_BASE64_64_SESSION}'
      - 'FORM_ENCRYPTION_KEY=${SERVICE_BASE64_64_FORM}'
      - 'MONGO_URI=mongodb://mongo:27017/heyform'
      - REDIS_HOST=keydb
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${SERVICE_PASSWORD_KEYDB}


adding  - REDIS_PASSWORD=${SERVICE_PASSWORD_KEYDB} fixes the issue.
