### ISSUE TITLE
Coolify not starting after install

### ISSUE THREAD

**Issue by ItzNeviKat** [coollabsio/coolify#43]
Hi! I'm tried to install coolify, but after installation I getting an error when loading admin page. `docker container list` returned this:
```
CONTAINER ID   IMAGE                 COMMAND                  CREATED         STATUS         PORTS       NAMES
de4208d382ff   bitnami/mongodb:4.4   "/opt/bitnami/script…"   4 minutes ago   Up 4 minutes   27017/tcp   coollabs-mongodb_mongodb.1.oxxaiewkfp00hf2gww2e80t4x
```
I tried to manually run coolify with `docker run -d -p3000:3000 --name coolify coolify`, but in logs I have an error:
```
> coolify@1.0.11 start /usr/src/app
> NODE_ENV=production node api/server

connection error: MongooseServerSelectionError: getaddrinfo ENOTFOUND coollabs-mongodb
    at NativeConnection.Connection.openUri (/usr/src/app/node_modules/.pnpm/mongoose@5.12.8/node_modules/mongoose/lib/connection.js:846:32)
    at /usr/src/app/node_modules/.pnpm/mongoose@5.12.8/node_modules/mongoose/lib/index.js:351:10
    at /usr/src/app/node_modules/.pnpm/mongoose@5.12.8/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/usr/src/app/node_modules/.pnpm/mongoose@5.12.8/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/usr/src/app/node_modules/.pnpm/mongoose@5.12.8/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/usr/src/app/node_modules/.pnpm/mongoose@5.12.8/node_modules/mongoose/lib/index.js:350:20)
    at Object.<anonymous> (/usr/src/app/api/server.js:45:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'coollabs-mongodb:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
```

Can you help me, please? Thank you for this product!

**Comment by ItzNeviKat** [comment]
I'm shocked... The problem was that I was creating a Github Application on my account. When I did this on the organization's account, it worked!
```
CONTAINER ID   IMAGE                 COMMAND                  CREATED          STATUS          PORTS                                                                      NAMES
c78ebf78017b   traefik:v2.4          "/entrypoint.sh --ap…"   12 seconds ago   Up 11 seconds   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   coollabs-coolify_proxy.1.bj1jdd38yrbtb0qpdjcld7z46
0622c5f1befe   coolify:latest        "docker-entrypoint.s…"   16 seconds ago   Up 14 seconds   3000/tcp                                                                   coollabs-coolify_coolify.1.x0g6qufdcljepltxnu6x6u8e8
ad1b1c06a14e   bitnami/mongodb:4.4   "/opt/bitnami/script…"   5 minutes ago    Up 5 minutes    27017/tcp                                                                  coollabs-mongodb_mongodb.1.v6fwu1yqlellgwrcxkk1i44qn
```

**Comment by ItzNeviKat** [comment]
The problem was solved. I'm created a Github App with name including ' symbol, that breaks env file.
