### ISSUE TITLE
[Bug]: API HTTP 500 on /applications

### ISSUE THREAD

**Issue by dokime7** [coollabsio/coolify#4495]
### Error Message and Logs

I've got a HTTP 500 error when I request `/api/v1/applications`
I restarted the server but the error persists.

If I go to the endpoint from a browser I get (without being connected):
```
500 
Error: Unmatched '}'
```

Logs on storage/logs/laravel.log:
```
[2024-12-06 12:04:56] production.ERROR: Unmatched '}' {"exception":"[object] (ParseError(code: 0): Unmatched '}' at /var/www/html/app/Http/Controllers/Api/ApplicationsController.php:2854)
[stacktrace]
#0 /var/www/html/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1115): is_a()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1052): Illuminate\\Routing\\Route->controllerMiddleware()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(820): Illuminate\\Routing\\Route->gatherMiddleware()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(802): Illuminate\\Routing\\Router->gatherRouteMiddleware()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#11 /var/www/html/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#30 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#31 {main}
"} 
```

### Steps to Reproduce

Call /applications endpoint:
`curl /api/v1/applications`

### Coolify Version

v4.0.0-beta.375

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

### Additional Information

Downgrade to v4.0.0-beta.374 doesn't fix the issue.

**Comment by dokime7** [comment]
Hmmm, seems to be a bad code copy/paste at the end of file:
https://github.com/coollabsio/coolify/blob/main/app/Http/Controllers/Api/ApplicationsController.php

**Comment by dokime7** [comment]
Removing all lines from https://github.com/coollabsio/coolify/blob/main/app/Http/Controllers/Api/ApplicationsController.php#L2831 to the end fix the issue.

**Comment by pnearing** [comment]
This  error also occurs on the cloud verison: ![Image](https://github.com/user-attachments/assets/150cbb4d-ce5b-45be-a290-b7efac3a78f0)

**Comment by MrLexisDev** [comment]
+1

**Comment by andrasbacsai** [comment]
It is fixed with https://github.com/coollabsio/coolify/pull/4505 in v367
