### ISSUE TITLE
[Bug]: Unable to deploy Next.js application with Dockerfile

### ISSUE THREAD

**Issue by jlimas** [coollabsio/coolify#4531]
### Error Message and Logs

Unable to deploy next.js application using Dockerfile. Seems to be asking for env vars which doesn't happen when I run a build locally.

```
2024-Dec-10 06:16:52.337965
#15 78.75 Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
2024-Dec-10 06:16:52.337965
#15 78.75     at createClientComponentClient (/app/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:47:11)
2024-Dec-10 06:16:52.337965
#15 78.75     at /app/.next/server/chunks/3763.js:66:108
2024-Dec-10 06:16:52.337965
#15 78.76 
2024-Dec-10 06:16:52.337965
#15 78.76 > Build error occurred
2024-Dec-10 06:16:52.337965
#15 78.76 Error: Failed to collect page data for /bots/[botId]/[state]
2024-Dec-10 06:16:52.337965
#15 78.76     at /app/node_modules/next/dist/build/utils.js:1158:15 {
2024-Dec-10 06:16:52.337965
#15 78.76   type: 'Error'
2024-Dec-10 06:16:52.337965
#15 78.76 }
2024-Dec-10 06:16:52.337965
#15 78.92 error Command failed with exit code 1.
2024-Dec-10 06:16:52.337965
#15 78.92 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024-Dec-10 06:16:52.337965
#15 ERROR: process "/bin/sh -c if [ -f yarn.lock ]; then yarn run build;   elif [ -f package-lock.json ]; then npm run build;   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build;   else echo \"Lockfile not found.\" && exit 1;   fi" did not complete successfully: exit code: 1
```

### Steps to Reproduce

1. Create a Dockerfile, using the official recommended for Next.js
2. Trigger a deploy.

### Coolify Version

v4.0.0-beta.376

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12

**Comment by peaklabs-dev** [comment]
You need to provide these env variables otherwise it will fail also can you please show me the Dockerfile you are having problems with.
