### ISSUE TITLE
[Bug]: Cant deploy nextjs app

### ISSUE THREAD

**Issue by paaauldev** [coollabsio/coolify#4619]
### Error Message and Logs

Im getting this error while installing any package fom npmjs, im using pnpm with nixpack, for example:

`#11 64.81  WARN  GET https://registry.npmjs.org/oauth4webapi/-/oauth4webapi-3.1.2.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.`

And after 3 retry
```
#11 255.3  ERR_SOCKET_TIMEOUT  request to https://registry.npmjs.org/oauth4webapi/-/oauth4webapi-3.1.2.tgz failed, reason: Socket timeout
#11 255.3 
#11 255.3 FetchError: request to https://registry.npmjs.org/oauth4webapi/-/oauth4webapi-3.1.2.tgz failed, reason: Socket timeout
#11 255.3     at ClientRequest.<anonymous> (/nix/store/lx2wfmprgj37h58nv3zry2wya37xlgm1-pnpm/dist/pnpm.cjs:66954:18)
#11 255.3     at ClientRequest.emit (node:events:517:28)
#11 255.3     at TLSSocket.socketErrorListener (node:_http_client:501:9)
#11 255.3     at TLSSocket.emit (node:events:529:35)
#11 255.3     at emitErrorNT (node:internal/streams/destroy:151:8)
#11 255.3     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
#11 255.3     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
#11 ERROR: process "/bin/bash -ol pipefail -c pnpm install" did not complete successfully: exit code: 1
------
 > [ 7/11] RUN  pnpm install:
255.3  ERR_SOCKET_TIMEOUT  request to https://registry.npmjs.org/oauth4webapi/-/oauth4webapi-3.1.2.tgz failed, reason: Socket timeout
255.3 
255.3 FetchError: request to https://registry.npmjs.org/oauth4webapi/-/oauth4webapi-3.1.2.tgz failed, reason: Socket timeout
255.3     at ClientRequest.<anonymous> (/nix/store/lx2wfmprgj37h58nv3zry2wya37xlgm1-pnpm/dist/pnpm.cjs:66954:18)
255.3     at ClientRequest.emit (node:events:517:28)
255.3     at TLSSocket.socketErrorListener (node:_http_client:501:9)
255.3     at TLSSocket.emit (node:events:529:35)
255.3     at emitErrorNT (node:internal/streams/destroy:151:8)
255.3     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
255.3     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
------
Dockerfile:20
--------------------
  18 |     ENV NIXPACKS_PATH=/app/node_modules/.bin:$NIXPACKS_PATH
  19 |     COPY . /app/.
  20 | >>> RUN  pnpm install
  21 |     
  22 |     # build phase
--------------------
ERROR: failed to solve: process "/bin/bash -ol pipefail -c pnpm install" did not complete successfully: exit code: 1
Deployment failed. Removing the new version of your application.
```

I have tried with other projects and same issue. Im using as "Install Command" pnpm install

### Steps to Reproduce

1. Build any nextjs app from github repository
2. Use pnpm install as install command

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 LTS

### Additional Information

Before migrating from an old server all was working fine with same settings, but when I migrate all and try to deploy this problem has begin

**Comment by paaauldev** [comment]
Now works fine, it seems like it was a temporary bug.

**Comment by mr-scrpt** [comment]
I am facing this error as well. Is there a solution?
At first I thought that maybe it's because when installing nextjs I choose that the app folder will be inside src. But no, I've tried several times to initialise the project and I can't get a completely clean nextjs application to run
