### ISSUE TITLE
[Bug]: Transactional Emails Failing to Send, Confusing documentation

### ISSUE THREAD

**Issue by tatarmb4s** [coollabsio/coolify#4695]
#### Description
When attempting to send transactional emails using Coolify, both SMTP and Resend methods failed. Below are the detailed errors encountered for each method. On the main window where I send the test it shows Success, but nothing happens.

---

##### **Using Resend**
**Error:** [Horizon Error Details](https://INSTANCE/horizon/failed/6aeaf10a-6614-47e1-99bb-6e442fff46df)

https://INSTANCE/horizon/failed/

ID
538c1074-597d-4563-85f7-b01c2e25583d
Queue
high
Attempts
5
Retries
0
Tags
Pushed
2024-12-28 22:41:08
Failed
2024-12-28 22:41:08

```
TypeError: Illuminate\Mail\MailManager::getConfig(): Argument #1 ($name) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php on line 114 and defined in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php:506
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(114): Illuminate\Mail\MailManager->getConfig()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(101): Illuminate\Mail\MailManager->resolve()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(79): Illuminate\Mail\MailManager->get()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(624): Illuminate\Mail\MailManager->mailer()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(359): Illuminate\Mail\MailManager->__call()
#5 /var/www/html/app/Notifications/Channels/EmailChannel.php(22): Illuminate\Support\Facades\Facade::__callStatic()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): App\Notifications\Channels\EmailChannel->send()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->{closure:Illuminate\Notifications\NotificationSender::sendNow():101}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(101): Illuminate\Notifications\NotificationSender->withLocale()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(54): Illuminate\Notifications\NotificationSender->sendNow()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php(119): Illuminate\Notifications\ChannelManager->sendNow()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Notifications\SendQueuedNotifications->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::{closure:Illuminate\Container\BoundMethod::call():35}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\BoundMethod::call()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(126): Illuminate\Container\Container->call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->{closure:Illuminate\Bus\Dispatcher::dispatchNow():123}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->{closure:Illuminate\Pipeline\Pipeline::prepareDestination():142}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(130): Illuminate\Pipeline\Pipeline->then()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->{closure:Illuminate\Queue\CallQueuedHandler::dispatchThroughMiddleware():123}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Middleware/RateLimited.php(59): Illuminate\Pipeline\Pipeline->{closure:Illuminate\Pipeline\Pipeline::prepareDestination():142}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Queue\Middleware\RateLimited->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():158}:159}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Pipeline\Pipeline->then()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(441): Illuminate\Queue\Jobs\Job->fire()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(391): Illuminate\Queue\Worker->process()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(178): Illuminate\Queue\Worker->runJob()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\Queue\Worker->daemon()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\Queue\Console\WorkCommand->runWorker()
#34 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::{closure:Illuminate\Container\BoundMethod::call():35}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\BoundMethod::call()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\Container\Container->call()
#41 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\Component\Console\Command\Command->run()
#43 /var/www/html/vendor/symfony/console/Application.php(1094): Illuminate\Console\Command->run()
#44 /var/www/html/vendor/symfony/console/Application.php(342): Symfony\Component\Console\Application->doRunCommand()
#45 /var/www/html/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRun()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(198): Symfony\Component\Console\Application->run()
#47 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#48 {main}
...
```

**Context:**
```json
{
  "notifiables": {
    "class": "App\\Models\\Team",
    "id": [
      0
    ],
    "relations": [],
    "connection": "pgsql",
    "collectionClass": null
  },
  "notification": {
    "emails": "tatar.matyas.bence@t42.hu",
    "channel": "email",
    "id": "cface829-6542-4bc6-9972-9614cd36f256",
    "queue": "high"
  },
  "channels": [
    "App\\Notifications\\Channels\\EmailChannel"
  ],
  "tries": 5,
  "queue": "high",
  "middleware": [
    {
      "limiterName": "email",
      "shouldRelease": true
    }
  ]
}

```

---

##### **Using SMTP**
**Error:** (Horizon Error Details for SMTP)

ID
e2fa813a-6bbc-4c23-a05c-b1916f91afbe
Queue
high
Attempts
5
Retries
0
Tags
Pushed
2024-12-28 22:33:28
Failed
2024-12-28 22:33:29

```
TypeError: Illuminate\Mail\MailManager::getConfig(): Argument #1 ($name) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php on line 114 and defined in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php:506
--
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(114): Illuminate\Mail\MailManager->getConfig()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(101): Illuminate\Mail\MailManager->resolve()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(79): Illuminate\Mail\MailManager->get()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(624): Illuminate\Mail\MailManager->mailer()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(359): Illuminate\Mail\MailManager->__call()
#5 /var/www/html/app/Notifications/Channels/EmailChannel.php(22): Illuminate\Support\Facades\Facade::__callStatic()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): App\Notifications\Channels\EmailChannel->send()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->{closure:Illuminate\Notifications\NotificationSender::sendNow():101}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(101): Illuminate\Notifications\NotificationSender->withLocale()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(54): Illuminate\Notifications\NotificationSender->sendNow()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php(119): Illuminate\Notifications\ChannelManager->sendNow()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Notifications\SendQueuedNotifications->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::{closure:Illuminate\Container\BoundMethod::call():35}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\BoundMethod::call()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(126): Illuminate\Container\Container->call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->{closure:Illuminate\Bus\Dispatcher::dispatchNow():123}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->{closure:Illuminate\Pipeline\Pipeline::prepareDestination():142}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(130): Illuminate\Pipeline\Pipeline->then()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->{closure:Illuminate\Queue\CallQueuedHandler::dispatchThroughMiddleware():123}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Middleware/RateLimited.php(59): Illuminate\Pipeline\Pipeline->{closure:Illuminate\Pipeline\Pipeline::prepareDestination():142}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Queue\Middleware\RateLimited->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():158}:159}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Pipeline\Pipeline->then()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(441): Illuminate\Queue\Jobs\Job->fire()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(391): Illuminate\Queue\Worker->process()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(178): Illuminate\Queue\Worker->runJob()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\Queue\Worker->daemon()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\Queue\Console\WorkCommand->runWorker()
#34 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::{closure:Illuminate\Container\BoundMethod::call():35}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\BoundMethod::call()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\Container\Container->call()
#41 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\Component\Console\Command\Command->run()
#43 /var/www/html/vendor/symfony/console/Application.php(1094): Illuminate\Console\Command->run()
#44 /var/www/html/vendor/symfony/console/Application.php(342): Symfony\Component\Console\Application->doRunCommand()
#45 /var/www/html/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRun()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(198): Symfony\Component\Console\Application->run()
#47 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#48 {main}
...
```

```json
{
  "notifiables": {
    "class": "App\\Models\\Team",
    "id": [
      0
    ],
    "relations": [],
    "connection": "pgsql",
    "collectionClass": null
  },
  "notification": {
    "emails": "exampl@exampl.hu",
    "channel": "email",
    "id": "8f9d0989-ecdb-4f8f-a060-b64258dc8377",
    "queue": "high"
  },
  "channels": [
    "App\\Notifications\\Channels\\EmailChannel"
  ],
  "tries": 5,
  "queue": "high",
  "middleware": [
    {
      "limiterName": "email",
      "shouldRelease": true
    }
  ]
}
```

![Image](https://github.com/user-attachments/assets/71d53029-6a19-4b04-af0a-ddadd0ee561e)

![Image](https://github.com/user-attachments/assets/3da56cb0-b36c-42af-aaa3-4040919b0079)

### Steps to Reproduce

1. Set up transactional email
2. Try to send using SMTP or Resend

### Coolify Version

v4.0.0-beta.380

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

**Comment by tatarmb4s** [comment]
After setting up the `settings/email` I went to 
`/notifications/email` and set the following, its working using Resend:

![Image](https://github.com/user-attachments/assets/f7295811-95af-493e-95d7-99c083ba2ec7)

This time the test email was sent successfully. 
Then I went back to the `settings/email` tried both Resend and SMTP and this time it worked. 


This is confusing, I admit its my fault, but all what started this was the teams members page what redirected me to settings. The docs sais I have to use the Notifications → Email but Teams sent me to a non existing `settings/email#smtp`.

**Comment by tatarmb4s** [comment]
notifications/email is in smtp mode:   Test emails from `notifications/email` and `settings/email` fail.
notifications/email is in Resend mode: Test emails from `notifications/email` and `settings/email`  success.

The  `settings/email` SMTP or Resend switch does not affect anything.

**Comment by peaklabs-dev** [comment]
Which SMTP provider are you using? Please make sure you are using the correct authentication method as described in the documentation:https://coolify.io/docs/knowledge-base/notifications/#smtp-server-configuration

**Comment by tatarmb4s** [comment]
I wanted to use M365 and configured it according to the docs. On paper everithing was fine.

**Comment by LarsArtmann** [comment]
I setup both notifications and transactional e-mail throw Resend.
All e-mails are send from the notification configuration.
If the notification configuration is not set transactional e-mail don't not work.

**Comment by JoeWHoward** [comment]
> If the notification configuration is not set transactional e-mail don't not work.

Thank you for this.  I had my Transactional email settings set up (via SMTP server from my email provider, MXRoute), but not notification settings.  I set the notification email settings and now my test emails are going through.

**Comment by dslandry** [comment]
@tatarmb4s My question is not linked to the issue but how were you able to access the logs from your coolify instance? I am also self hosting coolify on a VPS  but I don't know access the logs as you did. 
Also, I didn't see a documentation on the general architecture of coolify.

**Comment by peaklabs-dev** [comment]
A fix for this issue has been implemented and will be available in the next version. Thank you for your patience.
