### ISSUE TITLE
[Bug]: Coolify not starting

### ISSUE THREAD

**Issue by wallaceosmar** [coollabsio/coolify#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After installing in a new machine the version 3.2.0 the container of coolify stuck in an endless restart.

Log
```
> api@ start /app
> NODE_ENV=production npx -y prisma migrate deploy && npx prisma generate && npx prisma db seed && node index.js

Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "prod.db" at "file:../db/prod.db"

SQLite database prod.db created at file:../db/prod.db

43 migrations found in prisma/migrations

Applying migration `20220131142425_init`
Applying migration `20220210104005_redis_aol`
Applying migration `20220212142309_unique_secret_by_application`
Applying migration `20220217211304_dualcerts`
Applying migration `20220219231255_prmr_secrets`
Applying migration `20220220141136_public_portrange`
Applying migration `20220301101928_proxyhash`
Applying migration `20220304141408_service_secrets`
Applying migration `20220311213422_autodeploy`
Applying migration `20220320141424_phpmodules`
Applying migration `20220322135800_persistent_storage`
Applying migration `20220327180323_ghost`
Applying migration `20220402135305_python`
Applying migration `20220402210645_meilisearch`
Applying migration `20220405151428_wordpress_sftp`
Applying migration `20220407220809_unique_storage_fix`
Applying migration `20220408070805_added_expose_port`
Applying migration `20220418214843_persistent_storage_services`
Applying migration `20220419203408_multiply_dockerfile_locations`
Applying migration `20220420202031_deno_configurations`
Applying migration `20220420210057_branch_for_builds`
Applying migration `20220425071132_umami`
Applying migration `20220425075326_auto_update_coolify`
Applying migration `20220426125053_select_base_image`
Applying migration `20220427133656_hasura`
Applying migration `20220429202516_fider`
Applying migration `20220429214112_fider_correction`
Applying migration `20220430111953_ssl_dns_check_settings`
Applying migration `20220430124553_expose_port_for_services`
Applying migration `20220509130501_custom_plausible_script`
Applying migration `20220510081125_custom_wordpress_db`
Applying migration `20220517081328_traefik`
Applying migration `20220519095648_minio_apifqdn`
Applying migration `20220708132655_deployment_type_for_applications`
Applying migration `20220712083523_custom_port_git_sources`
Applying migration `20220718083646_moodle`
Applying migration `20220718114551_remote_docker_engine`
Applying migration `20220721084020_ssh_key`
Applying migration `20220722203927_ipaddress`
Applying migration `20220725191205_architecture`
Applying migration `20220726121333_fix_ssh_key`
Applying migration `20220806090621_fqdn_not_unique_anymore`
Applying migration `20220806102340_rde_ssh_local_port`

The following migrations have been applied:

migrations/
  └─ 20220131142425_init/
    └─ migration.sql
  └─ 20220210104005_redis_aol/
    └─ migration.sql
  └─ 20220212142309_unique_secret_by_application/
    └─ migration.sql
  └─ 20220217211304_dualcerts/
    └─ migration.sql
  └─ 20220219231255_prmr_secrets/
    └─ migration.sql
  └─ 20220220141136_public_portrange/
    └─ migration.sql
  └─ 20220301101928_proxyhash/
    └─ migration.sql
  └─ 20220304141408_service_secrets/
    └─ migration.sql
  └─ 20220311213422_autodeploy/
    └─ migration.sql
  └─ 20220320141424_phpmodules/
    └─ migration.sql
  └─ 20220322135800_persistent_storage/
    └─ migration.sql
  └─ 20220327180323_ghost/
    └─ migration.sql
  └─ 20220402135305_python/
    └─ migration.sql
  └─ 20220402210645_meilisearch/
    └─ migration.sql
  └─ 20220405151428_wordpress_sftp/
    └─ migration.sql
  └─ 20220407220809_unique_storage_fix/
    └─ migration.sql
  └─ 20220408070805_added_expose_port/
    └─ migration.sql
  └─ 20220418214843_persistent_storage_services/
    └─ migration.sql
  └─ 20220419203408_multiply_dockerfile_locations/
    └─ migration.sql
  └─ 20220420202031_deno_configurations/
    └─ migration.sql
  └─ 20220420210057_branch_for_builds/
    └─ migration.sql
  └─ 20220425071132_umami/
    └─ migration.sql
  └─ 20220425075326_auto_update_coolify/
    └─ migration.sql
  └─ 20220426125053_select_base_image/
    └─ migration.sql
  └─ 20220427133656_hasura/
    └─ migration.sql
  └─ 20220429202516_fider/
    └─ migration.sql
  └─ 20220429214112_fider_correction/
    └─ migration.sql
  └─ 20220430111953_ssl_dns_check_settings/
    └─ migration.sql
  └─ 20220430124553_expose_port_for_services/
    └─ migration.sql
  └─ 20220509130501_custom_plausible_script/
    └─ migration.sql
  └─ 20220510081125_custom_wordpress_db/
    └─ migration.sql
  └─ 20220517081328_traefik/
    └─ migration.sql
  └─ 20220519095648_minio_apifqdn/
    └─ migration.sql
  └─ 20220708132655_deployment_type_for_applications/
    └─ migration.sql
  └─ 20220712083523_custom_port_git_sources/
    └─ migration.sql
  └─ 20220718083646_moodle/
    └─ migration.sql
  └─ 20220718114551_remote_docker_engine/
    └─ migration.sql
  └─ 20220721084020_ssh_key/
    └─ migration.sql
  └─ 20220722203927_ipaddress/
    └─ migration.sql
  └─ 20220725191205_architecture/
    └─ migration.sql
  └─ 20220726121333_fix_ssh_key/
    └─ migration.sql
  └─ 20220806090621_fqdn_not_unique_anymore/
    └─ migration.sql
  └─ 20220806102340_rde_ssh_local_port/
    └─ migration.sql

All migrations have been successfully applied.
npm notice
npm notice New minor version of npm available! 8.15.0 -> 8.17.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.17.0>
npm notice Run `npm install -g npm@8.17.0` to update!
npm notice
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (3.15.2 | binary) to ./node_modules/.pnpm/@prisma+client@3.15.2_prisma@3.15.2/node_modules/@prisma/client in 1.16s
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

warn Versions of prisma@4.2.1 and @prisma/client@3.15.2 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
Running seed command `node prisma/seed.js` ...

🌱  The seed command has been executed.
Error: env/COOLIFY_WHITE_LABELED must be boolean
    at loadAndValidateEnvironment (/app/node_modules/.pnpm/env-schema@5.0.0/node_modules/env-schema/index.js:84:19)
    at loadAndValidateEnvironment (/app/node_modules/.pnpm/@fastify+env@4.1.0/node_modules/@fastify/env/index.js:8:20)
    at Plugin.exec (/app/node_modules/.pnpm/avvio@8.2.0/node_modules/avvio/plugin.js:130:19)
    at Boot.loadPlugin (/app/node_modules/.pnpm/avvio@8.2.0/node_modules/avvio/plugin.js:272:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errors: [
    {
      instancePath: '/COOLIFY_WHITE_LABELED',
      schemaPath: '#/properties/COOLIFY_WHITE_LABELED/type',
      keyword: 'type',
      params: [Object],
      message: 'must be boolean'
    }
  ]
}
 ELIFECYCLE  Command failed with exit code 1.

> api@ start /app
> NODE_ENV=production npx -y prisma migrate deploy && npx prisma generate && npx prisma db seed && node index.js

Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "prod.db" at "file:../db/prod.db"

43 migrations found in prisma/migrations


No pending migrations to apply.
```

### Steps To Reproduce

1. Install coolify wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh
2. docker stats or docker ps -a

### Version

3.2.0

**Comment by andrasbacsai** [comment]
The new version will be released in a few minutes.

**Comment by andrasbacsai** [comment]
Released. Please let me know if it still does not work!
