### ISSUE TITLE
[Bug]: Missing column after restart

### ISSUE THREAD

**Issue by JanSeW** [coollabsio/coolify#903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After I updated and restarted my server Coolify is in an endless start loop. It seems like there is a missing column in the main database.

`docker logs` output:
``` 
> api@ start /app
> NODE_ENV=production pnpm prisma migrate deploy && pnpm prisma generate && pnpm prisma db seed && node index.js

Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "prod.db" at "file:../db/prod.db"

73 migrations found in prisma/migrations


No pending migrations to apply.
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.5.0 | library) to ./node_modules/.pnpm/@prisma+client@4.5.0_prisma@4.5.0/node_modules/@prisma/client in 1.18s
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

Running seed command `node prisma/seed.js` ...
PrismaClientKnownRequestError:
Invalid `prisma.setting.findFirst()` invocation:


The column `main.Setting.proxyPassword` does not exist in the current database.
    at RequestHandler.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.5.0_prisma@4.5.0/node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (/app/node_modules/.pnpm/@prisma+client@4.5.0_prisma@4.5.0/node_modules/@prisma/client/runtime/index.js:30856:12)
    at async PrismaClient._request (/app/node_modules/.pnpm/@prisma+client@4.5.0_prisma@4.5.0/node_modules/@prisma/client/runtime/index.js:31836:16)
    at async main (/app/prisma/seed.js:20:24) {
  code: 'P2022',
  clientVersion: '4.5.0',
  meta: { column: 'main.Setting.proxyPassword' }
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: node prisma/seed.js
 ELIFECYCLE  Command failed with exit code 1.

```

`Docker version 23.0.0, build e92dd87`

Unfortunately I can not downgrade due to #901 .

Anyone with an idea?

### Steps To Reproduce

1. Use newest verison of Coolify.
2. Update your server with `apt update && apt upgrade`
3. Restart your server with `restart now`
4. You should see all docker containers are spinning up but Coolify crashes after around 20s

### Version

3.12.18

**Comment by andrasbacsai** [comment]
It looks like the Coolify version that would like to start is an old one. 

Please try to reinstall Coolify (your configurations will be saved) with the following command:
`wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh`

Let me know if it still does not work.
