### ISSUE TITLE
Might need to upgrade `node:lts`

### ISSUE THREAD

**Issue by tomatrow** [coollabsio/coolify#92]
Hi,

Coolify is pretty cool, thanks for writing it. 

I'm on Ubuntu 21.04

I had this unsupported python error when installing it initially: 

<details>
<summary>Error Log</summary>

```
Sending build context to Docker daemon  2.045MB

Step 1/15 : FROM node:lts
 ---> db40ea2d00ea
Step 2/15 : LABEL coolify-preserve=true
 ---> Using cache
 ---> 8fc9ac2f2a9c
Step 3/15 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 3e844c17b3cb
Step 4/15 : RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-20.10.6.tgz | tar -xzvf - docker/docker -C . --strip-components 1
 ---> Using cache
 ---> 593f1b7b89be
Step 5/15 : RUN mv /usr/src/app/docker /usr/bin/docker
 ---> Using cache
 ---> bbca9be7e07e
Step 6/15 : RUN curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o /usr/bin/envsubst
 ---> Using cache
 ---> 47c7a6510d59
Step 7/15 : RUN curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o /usr/bin/jq
 ---> Using cache
 ---> b47bcfb64e14
Step 8/15 : RUN chmod +x /usr/bin/envsubst /usr/bin/jq /usr/bin/docker
 ---> Using cache
 ---> d9336c52b64f
Step 9/15 : RUN curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
 ---> Using cache
 ---> 87369b22f6a3
Step 10/15 : COPY ./*package.json .
 ---> Using cache
 ---> 1dbaad40f058
Step 11/15 : RUN pnpm install
 ---> Running in 02eaeebc4406
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 22, reused 0, downloaded 0, added 0
Progress: resolved 47, reused 0, downloaded 27, added 0
Progress: resolved 68, reused 0, downloaded 49, added 0
Progress: resolved 96, reused 0, downloaded 75, added 0
Progress: resolved 141, reused 0, downloaded 115, added 0
Progress: resolved 184, reused 0, downloaded 155, added 0
Progress: resolved 269, reused 0, downloaded 234, added 0
Progress: resolved 354, reused 0, downloaded 309, added 0
Progress: resolved 449, reused 0, downloaded 392, added 0
Packages: +454
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 455, reused 0, downloaded 445, added 26
Progress: resolved 455, reused 0, downloaded 450, added 450
Progress: resolved 455, reused 0, downloaded 452, added 452
.../bcrypt@5.0.1/node_modules/bcrypt install$ node-pre-gyp install --fallback-to-build
.../esbuild@0.12.28/node_modules/esbuild postinstall$ node install.js
.../node_modules/svelte-preprocess postinstall$ echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."
.../node_modules/svelte-preprocess postinstall: [svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...
.../node_modules/svelte-preprocess postinstall: Done
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp info it worked if it ends with ok
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp info using node-pre-gyp@1.0.5
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp info using node@14.17.6 | linux | x64
Progress: resolved 455, reused 0, downloaded 454, added 454, done
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp info check checked for "/usr/src/app/node_modules/.pnpm/bcrypt@5.0.1/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! install response status 403 Forbidden on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz 
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.0.1 and node@14.17.6 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp WARN Hit error response status 403 Forbidden on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz 
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp info it worked if it ends with ok
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp info using node-gyp@8.2.0
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp info using node@14.17.6 | linux | x64
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp info ok 
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp info it worked if it ends with ok
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp info using node-gyp@8.2.0
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp info using node@14.17.6 | linux | x64
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python 
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python Python is not set from command line or npm configuration
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python Python is not set from environment variable PYTHON
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python checking if "python3" can be used
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - executable path is "/usr/bin/python3"
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - version is "3.5.3"
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - version is 3.5.3 - should be >=3.6.0
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python checking if "python" can be used
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - executable path is "/usr/bin/python"
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - version is "2.7.13"
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - version is 2.7.13 - should be >=3.6.0
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python 
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python **********************************************************
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python You need to install the latest version of Python.
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python you can try one of the following options:
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python   (accepted by both node-gyp and npm)
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - Set the environment variable PYTHON
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python - Set the npm configuration variable python:
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python For more information consult the documentation at:
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python **********************************************************
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! find Python 
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! configure error 
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! stack Error: Could not find any Python installation to use
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! stack     at PythonFinder.fail (/usr/local/pnpm-global/5/node_modules/.pnpm/pnpm@6.15.1/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:330:47)
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! stack     at PythonFinder.runChecks (/usr/local/pnpm-global/5/node_modules/.pnpm/pnpm@6.15.1/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:159:21)
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pnpm@6.15.1/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:266:16)
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/pnpm-global/5/node_modules/.pnpm/pnpm@6.15.1/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:297:7)
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! stack     at ChildProcess.exithandler (child_process.js:381:7)
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! System Linux 5.11.0-25-generic
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! command "/usr/local/bin/node" "/usr/local/pnpm-global/5/node_modules/.pnpm/pnpm@6.15.1/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/src/app/node_modules/.pnpm/bcrypt@5.0.1/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/src/app/node_modules/.pnpm/bcrypt@5.0.1/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! cwd /usr/src/app/node_modules/.pnpm/bcrypt@5.0.1/node_modules/bcrypt
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! node -v v14.17.6
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! node-gyp -v v8.2.0
.../bcrypt@5.0.1/node_modules/bcrypt install: gyp ERR! not ok 
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! build error 
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/pnpm-global/5/node_modules/.pnpm/pnpm@6.15.1/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/.pnpm/bcrypt@5.0.1/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/src/app/node_modules/.pnpm/bcrypt@5.0.1/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.5/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! System Linux 5.11.0-25-generic
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.5/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! cwd /usr/src/app/node_modules/.pnpm/bcrypt@5.0.1/node_modules/bcrypt
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! node -v v14.17.6
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! node-pre-gyp -v v1.0.5
.../bcrypt@5.0.1/node_modules/bcrypt install: node-pre-gyp ERR! not ok 
.../bcrypt@5.0.1/node_modules/bcrypt install: Failed to execute '/usr/local/bin/node /usr/local/pnpm-global/5/node_modules/.pnpm/pnpm@6.15.1/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/.pnpm/bcrypt@5.0.1/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/src/app/node_modules/.pnpm/bcrypt@5.0.1/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
.../bcrypt@5.0.1/node_modules/bcrypt install: Failed
 ELIFECYCLE  Command failed with exit code 1.
```
</details>

After replacing `FROM node:lts` with `FROM node:latest` in `install/Dockerfile-new`, I was able to continue the installation in `coollabs-installers/index.php` normally. I know this ubuntu version isn't tested, but I'm guessing the installer will work fine with a slight bump to the node image version.

Output of `name -a`
Linux localhost 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andrasbacsai** [comment]
Hey @tomatrow !

The installation script has been replaced with the new v2 of Coolify, so this issue is deprecated. Closing it. Thanks for reporting!
